#### Гладова Анастасия, гр. ИУ5Ц-81Б (ИУ5-61)

#### Рубежный контроль №1

#### Вариант №2

Для заданного набора данных проведите обработку пропусков в данных для одного категориального и одного количественного признака. 
Какие способы обработки пропусков в данных для категориальных и количественных признаков Вы использовали? 
Какие признаки Вы будете использовать для дальнейшего построения моделей машинного обучения и почему?

In [35]:
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn
import matplotlib.pyplot as plt
%matplotlib inline
sns.set(style="ticks")

In [36]:
#загружаем датасет
data=pd.read_csv('fifa19.csv', sep=",")

In [37]:
# размер набора данных
data.shape

(18207, 89)

In [38]:
# типы колонок
data.dtypes

Unnamed: 0                    int64
ID                            int64
Name                         object
Age                           int64
Photo                        object
Nationality                  object
Flag                         object
Overall                       int64
Potential                     int64
Club                         object
Club Logo                    object
Value                        object
Wage                         object
Special                       int64
Preferred Foot               object
International Reputation    float64
Weak Foot                   float64
Skill Moves                 float64
Work Rate                    object
Body Type                    object
Real Face                    object
Position                     object
Jersey Number               float64
Joined                       object
Loaned From                  object
Contract Valid Until         object
Height                       object
Weight                      

In [39]:
# проверим есть ли пропущенные значения
data.isnull().sum()

Unnamed: 0                      0
ID                              0
Name                            0
Age                             0
Photo                           0
Nationality                     0
Flag                            0
Overall                         0
Potential                       0
Club                          241
Club Logo                       0
Value                           0
Wage                            0
Special                         0
Preferred Foot                 48
International Reputation       48
Weak Foot                      48
Skill Moves                    48
Work Rate                      48
Body Type                      48
Real Face                      48
Position                       60
Jersey Number                  60
Joined                       1553
Loaned From                 16943
Contract Valid Until          289
Height                         48
Weight                         48
LS                           2085
ST            

In [40]:
#Обработка пропусков в числовых данных

#Jersey Number    48      float64

# Фильтр по колонкам с пропущенными значениями
data_num = data[["Jersey Number"]]
data_num

Jersey Number
0               10.0
1                7.0
2               10.0
3                1.0
4                7.0
5               10.0
6               10.0
7                9.0
8               15.0
9                1.0
10               9.0
11               8.0
12              10.0
13              21.0
14              13.0
15              21.0
16               9.0
17               7.0
18              22.0
19               1.0
20               5.0
21              21.0
22               1.0
23              10.0
24               3.0
25              10.0
26              10.0
27              14.0
28              10.0
29              10.0
...              ...
18177           32.0
18178           30.0
18179           31.0
18180           30.0
18181           32.0
18182           28.0
18183           44.0
18184           33.0
18185           19.0
18186           26.0
18187           33.0
18188           38.0
18189           24.0
18190           32.0
18191           24.0
18192           31.0
18193            4.0
18194           32.0
18195           23.0
18196           26.0
18197           14.0
18198           22.0
18199           65.0
18200           21.0
18201           29.0
18202           22.0
18203           21.0
18204           33.0
18205           34.0
18206           33.0

[18207 rows x 1 columns]

In [41]:
# Фильтр по пустым значениям поля Jersey Number
data[data['Jersey Number'].isnull()]

Unnamed: 0      ID             Name  Age  \
5018         5018  153160        R. Raldes   37   
6736         6736  175393          J. Arce   33   
7922         7922  195905     L. Gutiérrez   33   
9905         9905  226044        R. Vargas   23   
10628       10628  216751      D. Bejarano   26   
13236       13236  177971       J. McNulty   33   
13237       13237  195380       J. Barrera   29   
13238       13238  139317         J. Stead   35   
13239       13239  240437      A. Semprini   20   
13240       13240  209462       R. Bingham   24   
13241       13241  219702     K. Dankowski   21   
13242       13242  225590        I. Colman   23   
13243       13243  233782        M. Feeney   19   
13244       13244  239158         R. Minor   30   
13245       13245  242998           Klauss   21   
13246       13246  244022       I. Sissoko   22   
13247       13247  189238          F. Hart   28   
13248       13248  211511    L. McCullough   24   
13249       13249  224055        Li Yunqiu   27   
13250       13250  244535        F. Garcia   29   
13251       13251  134968     R. Haemhouts   34   
13252       13252  225336        E. Binaku   22   
13253       13253  171320        G. Miller   31   
13254       13254  246328       A. Aidonis   17   
13255       13255  196921         L. Sowah   25   
13256       13256  202809        R. Deacon   26   
13257       13257  226617    Jang Hyun Soo   25   
13258       13258  230713      A. Al Malki   23   
13259       13259  234809      E. Guerrero   27   
13260       13260  246073          Hernáiz   20   
13261       13261  221498    H. Al Mansour   25   
13262       13262  244026          H. Paul   24   
13263       13263  244538         S. Bauer   25   
13264       13264  201019       M. Chergui   29   
13265       13265  221499       D. Gardner   28   
13266       13266  237371     L. Bengtsson   20   
13267       13267  242491     F. Jaramillo   22   
13268       13268  153148       L. Garguła   37   
13269       13269  244540        S. Rivera   26   
13270       13270  245564         Vinicius   19   
13271       13271  213821     F. Sepúlveda   26   
13272       13272  240701        L. Spence   22   
13273       13273  242237       B. Lepistu   25   
13274       13274  244029      A. Abruscia   27   
13275       13275  244541      E. González   23   
13276       13276  211006       M. Al Amri   26   
13277       13277  215102     J. Rebolledo   26   
13278       13278  246078       C. Mamengi   17   
13279       13279  239679     P. Mazzocchi   22   
13280       13280  244543        Y. Ammour   19   
13281       13281  212800   Jwa Joon Hyeop   27   
13282       13282  231232       O. Marrufo   25   
13283       13283  232256      Han Pengfei   25   
16450       16450  193911          S. Paul   31   
16539       16539  245167  L. Lalruatthara   23   
16793       16793  228192       E. Lyngdoh   31   
17129       17129  228198         J. Singh   26   
17339       17339  233526         S. Passi   23   
17436       17436  236452   D. Lalhlimpuia   20   
17539       17539  234508         C. Singh   21   

                                                Photo       Nationality  \
5018   https://cdn.sofifa.org/players/4/19/153160.png           Bolivia   
6736   https://cdn.sofifa.org/players/4/19/175393.png           Bolivia   
7922   https://cdn.sofifa.org/players/4/19/195905.png           Bolivia   
9905   https://cdn.sofifa.org/players/4/19/226044.png           Bolivia   
10628  https://cdn.sofifa.org/players/4/19/216751.png           Bolivia   
13236  https://cdn.sofifa.org/players/4/19/177971.png          Scotland   
13237  https://cdn.sofifa.org/players/4/19/195380.png         Nicaragua   
13238  https://cdn.sofifa.org/players/4/19/139317.png           England   
13239  https://cdn.sofifa.org/players/4/19/240437.png             Italy   
13240  https://cdn.sofifa.org/players/4/19/209462.png           England   
13241  https://cdn.sofifa.org/players/4/19/219702.png            Polan

In [42]:
# Запоминаем индексы строк с пустыми значениями
flt_index = data[data['Jersey Number'].isnull()].index
flt_index

Int64Index([ 5018,  6736,  7922,  9905, 10628, 13236, 13237, 13238, 13239,
            13240, 13241, 13242, 13243, 13244, 13245, 13246, 13247, 13248,
            13249, 13250, 13251, 13252, 13253, 13254, 13255, 13256, 13257,
            13258, 13259, 13260, 13261, 13262, 13263, 13264, 13265, 13266,
            13267, 13268, 13269, 13270, 13271, 13272, 13273, 13274, 13275,
            13276, 13277, 13278, 13279, 13280, 13281, 13282, 13283, 16450,
            16539, 16793, 17129, 17339, 17436, 17539],
           dtype='int64')

In [43]:
# Проверяем что выводятся нужные строки
data[data.index.isin(flt_index)]

Unnamed: 0      ID             Name  Age  \
5018         5018  153160        R. Raldes   37   
6736         6736  175393          J. Arce   33   
7922         7922  195905     L. Gutiérrez   33   
9905         9905  226044        R. Vargas   23   
10628       10628  216751      D. Bejarano   26   
13236       13236  177971       J. McNulty   33   
13237       13237  195380       J. Barrera   29   
13238       13238  139317         J. Stead   35   
13239       13239  240437      A. Semprini   20   
13240       13240  209462       R. Bingham   24   
13241       13241  219702     K. Dankowski   21   
13242       13242  225590        I. Colman   23   
13243       13243  233782        M. Feeney   19   
13244       13244  239158         R. Minor   30   
13245       13245  242998           Klauss   21   
13246       13246  244022       I. Sissoko   22   
13247       13247  189238          F. Hart   28   
13248       13248  211511    L. McCullough   24   
13249       13249  224055        Li Yunqiu   27   
13250       13250  244535        F. Garcia   29   
13251       13251  134968     R. Haemhouts   34   
13252       13252  225336        E. Binaku   22   
13253       13253  171320        G. Miller   31   
13254       13254  246328       A. Aidonis   17   
13255       13255  196921         L. Sowah   25   
13256       13256  202809        R. Deacon   26   
13257       13257  226617    Jang Hyun Soo   25   
13258       13258  230713      A. Al Malki   23   
13259       13259  234809      E. Guerrero   27   
13260       13260  246073          Hernáiz   20   
13261       13261  221498    H. Al Mansour   25   
13262       13262  244026          H. Paul   24   
13263       13263  244538         S. Bauer   25   
13264       13264  201019       M. Chergui   29   
13265       13265  221499       D. Gardner   28   
13266       13266  237371     L. Bengtsson   20   
13267       13267  242491     F. Jaramillo   22   
13268       13268  153148       L. Garguła   37   
13269       13269  244540        S. Rivera   26   
13270       13270  245564         Vinicius   19   
13271       13271  213821     F. Sepúlveda   26   
13272       13272  240701        L. Spence   22   
13273       13273  242237       B. Lepistu   25   
13274       13274  244029      A. Abruscia   27   
13275       13275  244541      E. González   23   
13276       13276  211006       M. Al Amri   26   
13277       13277  215102     J. Rebolledo   26   
13278       13278  246078       C. Mamengi   17   
13279       13279  239679     P. Mazzocchi   22   
13280       13280  244543        Y. Ammour   19   
13281       13281  212800   Jwa Joon Hyeop   27   
13282       13282  231232       O. Marrufo   25   
13283       13283  232256      Han Pengfei   25   
16450       16450  193911          S. Paul   31   
16539       16539  245167  L. Lalruatthara   23   
16793       16793  228192       E. Lyngdoh   31   
17129       17129  228198         J. Singh   26   
17339       17339  233526         S. Passi   23   
17436       17436  236452   D. Lalhlimpuia   20   
17539       17539  234508         C. Singh   21   

                                                Photo       Nationality  \
5018   https://cdn.sofifa.org/players/4/19/153160.png           Bolivia   
6736   https://cdn.sofifa.org/players/4/19/175393.png           Bolivia   
7922   https://cdn.sofifa.org/players/4/19/195905.png           Bolivia   
9905   https://cdn.sofifa.org/players/4/19/226044.png           Bolivia   
10628  https://cdn.sofifa.org/players/4/19/216751.png           Bolivia   
13236  https://cdn.sofifa.org/players/4/19/177971.png          Scotland   
13237  https://cdn.sofifa.org/players/4/19/195380.png         Nicaragua   
13238  https://cdn.sofifa.org/players/4/19/139317.png           England   
13239  https://cdn.sofifa.org/players/4/19/240437.png             Italy   
13240  https://cdn.sofifa.org/players/4/19/209462.png           England   
13241  https://cdn.sofifa.org/players/4/19/219702.png            Polan

In [44]:
# фильтр по колонке
data_num[data_num.index.isin(flt_index)]['Jersey Number']

5018    NaN
6736    NaN
7922    NaN
9905    NaN
10628   NaN
13236   NaN
13237   NaN
13238   NaN
13239   NaN
13240   NaN
13241   NaN
13242   NaN
13243   NaN
13244   NaN
13245   NaN
13246   NaN
13247   NaN
13248   NaN
13249   NaN
13250   NaN
13251   NaN
13252   NaN
13253   NaN
13254   NaN
13255   NaN
13256   NaN
13257   NaN
13258   NaN
13259   NaN
13260   NaN
13261   NaN
13262   NaN
13263   NaN
13264   NaN
13265   NaN
13266   NaN
13267   NaN
13268   NaN
13269   NaN
13270   NaN
13271   NaN
13272   NaN
13273   NaN
13274   NaN
13275   NaN
13276   NaN
13277   NaN
13278   NaN
13279   NaN
13280   NaN
13281   NaN
13282   NaN
13283   NaN
16450   NaN
16539   NaN
16793   NaN
17129   NaN
17339   NaN
17436   NaN
17539   NaN
Name: Jersey Number, dtype: float64

In [45]:
data_num_JerseyNumber = data_num[['Jersey Number']]
data_num_JerseyNumber.head()

Jersey Number
0           10.0
1            7.0
2           10.0
3            1.0
4            7.0

In [46]:
from sklearn.impute import SimpleImputer
from sklearn.impute import MissingIndicator

In [47]:
# Фильтр для проверки заполнения пустых значений
indicator = MissingIndicator()
mask_missing_values_only = indicator.fit_transform(data_num_JerseyNumber)
mask_missing_values_only

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [48]:
strategies=['mean', 'median','most_frequent']

In [49]:
def test_num_impute(strategy_param):
    imp_num = SimpleImputer(strategy=strategy_param)
    data_num_imp = imp_num.fit_transform(data_num_JerseyNumber)
    return data_num_imp[mask_missing_values_only]

In [50]:
strategies[0], test_num_impute(strategies[0])

('mean',
 array([19.54609577, 19.54609577, 19.54609577, 19.54609577, 19.54609577,
        19.54609577, 19.54609577, 19.54609577, 19.54609577, 19.54609577,
        19.54609577, 19.54609577, 19.54609577, 19.54609577, 19.54609577,
        19.54609577, 19.54609577, 19.54609577, 19.54609577, 19.54609577,
        19.54609577, 19.54609577, 19.54609577, 19.54609577, 19.54609577,
        19.54609577, 19.54609577, 19.54609577, 19.54609577, 19.54609577,
        19.54609577, 19.54609577, 19.54609577, 19.54609577, 19.54609577,
        19.54609577, 19.54609577, 19.54609577, 19.54609577, 19.54609577,
        19.54609577, 19.54609577, 19.54609577, 19.54609577, 19.54609577,
        19.54609577, 19.54609577, 19.54609577, 19.54609577, 19.54609577,
        19.54609577, 19.54609577, 19.54609577, 19.54609577, 19.54609577,
        19.54609577, 19.54609577, 19.54609577, 19.54609577, 19.54609577]))

In [51]:
strategies[1], test_num_impute(strategies[1])

('median',
 array([17., 17., 17., 17., 17., 17., 17., 17., 17., 17., 17., 17., 17.,
        17., 17., 17., 17., 17., 17., 17., 17., 17., 17., 17., 17., 17.,
        17., 17., 17., 17., 17., 17., 17., 17., 17., 17., 17., 17., 17.,
        17., 17., 17., 17., 17., 17., 17., 17., 17., 17., 17., 17., 17.,
        17., 17., 17., 17., 17., 17., 17., 17.]))

In [52]:
strategies[2], test_num_impute(strategies[2])

('most_frequent',
 array([8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
        8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
        8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8., 8.,
        8., 8., 8., 8., 8., 8., 8., 8., 8.]))

In [53]:
#Обработка пропусков в категориальных данных
#Club     241     object

In [54]:
cat_temp_data = data[['Club']]
cat_temp_data.head()

Club
0         FC Barcelona
1             Juventus
2  Paris Saint-Germain
3    Manchester United
4      Manchester City

In [55]:
cat_temp_data['Club'].unique()

array(['FC Barcelona', 'Juventus', 'Paris Saint-Germain',
       'Manchester United', 'Manchester City', 'Chelsea', 'Real Madrid',
       'Atlético Madrid', 'FC Bayern München', 'Tottenham Hotspur',
       'Liverpool', 'Napoli', 'Arsenal', 'Milan', 'Inter', 'Lazio',
       'Borussia Dortmund', 'Vissel Kobe', 'Olympique Lyonnais', 'Roma',
       'Valencia CF', 'Guangzhou Evergrande Taobao FC', 'FC Porto',
       'FC Schalke 04', 'Beşiktaş JK', 'LA Galaxy', 'Sporting CP',
       'Real Betis', 'Olympique de Marseille', 'RC Celta',
       'Bayer 04 Leverkusen', 'Real Sociedad', 'Villarreal CF',
       'Sevilla FC', 'SL Benfica', 'AS Saint-Étienne', 'AS Monaco',
       'Leicester City', 'Atalanta', 'Grêmio', 'Atlético Mineiro',
       'RB Leipzig', 'Ajax', 'Dalian YiFang FC', 'Everton',
       'West Ham United', '1. FC Köln', 'TSG 1899 Hoffenheim',
       'Shanghai SIPG FC', 'OGC Nice', 'Al Nassr',
       'Wolverhampton Wanderers', 'Borussia Mönchengladbach',
       'Hertha BSC', 'SV Werder

In [56]:
cat_temp_data[cat_temp_data['Club'].isnull()].shape

(241, 1)

In [57]:
# Импьютация константой
imp3 = SimpleImputer(missing_values=np.nan, strategy='constant', fill_value='!!!!!')
data_imp3 = imp3.fit_transform(cat_temp_data)
data_imp3

array([['FC Barcelona'],
       ['Juventus'],
       ['Paris Saint-Germain'],
       ...,
       ['Cambridge United'],
       ['Tranmere Rovers'],
       ['Tranmere Rovers']], dtype=object)

In [58]:
np.unique(data_imp3)

array([' SSV Jahn Regensburg', '!!!!!', '1. FC Heidenheim 1846',
       '1. FC Kaiserslautern', '1. FC Köln', '1. FC Magdeburg',
       '1. FC Nürnberg', '1. FC Union Berlin', '1. FSV Mainz 05',
       'AC Ajaccio', 'AC Horsens', 'AD Alcorcón', 'ADO Den Haag',
       'AEK Athens', 'AFC Wimbledon', 'AIK', 'AJ Auxerre', 'AS Béziers',
       'AS Monaco', 'AS Nancy Lorraine', 'AS Saint-Étienne', 'AZ Alkmaar',
       'Aalborg BK', 'Aarhus GF', 'Aberdeen', 'Accrington Stanley',
       'Adelaide United', 'Ajax', 'Akhisar Belediyespor', 'Al Ahli',
       'Al Batin', 'Al Faisaly', 'Al Fateh', 'Al Fayha', 'Al Hazem',
       'Al Hilal', 'Al Ittihad', 'Al Nassr', 'Al Qadisiyah', 'Al Raed',
       'Al Shabab', 'Al Taawoun', 'Al Wehda', 'Alanyaspor', 'Albacete BP',
       'Alianza Petrolera', 'Amiens SC', 'América FC (Minas Gerais)',
       'América de Cali', 'Angers SCO', 'Antalyaspor',
       'Argentinos Juniors', 'Arka Gdynia', 'Arsenal', 'Ascoli',
       'Aston Villa', 'Atalanta', 'Athletic Club

In [59]:
data_imp3[data_imp3=='!!!!!'].size

241